name: Java CI with Gradle

on:
  push:
    branches: [ "1.12.x" ]
  pull_request:
    branches: [ "1.12.x" ]

permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: Change perms
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Automatic build
          path: build/libs